name: PluginManager
version: 1.1.1
author: Justix
main: net.dev.pluginmanager.main.Main
api-version: 1.13

commands:
      pluginmanager:
        aliases:
        - pluginm
        - pmanager
        - pman